spring.application.name=myjourney

# DB configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/travelDetails
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

# Server Configuration
# server.servlet.context-path=/api/v1

# JPA/Hibernate Configuration
spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true
#spring.jpa.properties.hibernate.format_sql=false

# # Database Initialization
# spring.jpa.defer-datasource-initialization=true
# spring.sql.init.mode=always
# spring.sql.init.data-locations=classpath:data.sql

#security config
# spring.security.user.name=anuj
# spring.security.user.password=pass

debug=true

# JWT Secret Key
jwt.secretKey=asdfnads9f67as98dfgvaisudhfa98s67dfy89aishudfuavs89gfvyasi8df76a89sdf7y